import "@styles/globals.css"
import Footer from "@components/footer/Footer"
import Navbar from "@components/navbar/Navbar"

export const metadata = {
  title: "MoonTourus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main md:m-[12px]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
